### ISSUE TITLE
disconnect error 

### ISSUE THREAD

**Issue by kleunen** [redboltz/mqtt_cpp#112]
Hello Takatoshi Kondo, 

I have been using the mqtt_cpp library and I it works very well and I am very happy with using it. There is however one thing I noticed. In asio, if you call 'close' on a socket, the read or write operation callback will be called with a error code 'boost::asio::error::operation_aborted'. 

In your code, if I call disconnect on the mqtt client connection, the disconnect handler will be called. However I do not know in this callback if this was a willful or unwillful disconnect. If an error/remote disconnect occurs, for example, I want to start a reconnect operation. If no error occurs (shutdown is called from within the code), I just want to cancel the connection and shutdown the application cleanly. 

Is it possible to add an error code to the disconnect operation ? I use a separate boolean now, but the error code would be more clean and in line with asio. 

Also it seems the error handler is not called when a disconnect occurs ?

**Comment by redboltz** [comment]
Hello @kleunen ,

> In your code, if I call disconnect on the mqtt client connection, the disconnect handler will be called. 

Are you talking about client side? If it is, close_handler will be called. You can set the close_handler using [set_close_handler](http://redboltz.github.io/contents/mqtt/classmqtt_1_1client.html#a4d87c2b9c4529c875264e5f1270d2c80).

mqtt_cpp's `disconnect()` sends MQTT disconnect packet but not close the socket from the client side.

https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L771

When the server receives the MQTT disconnect packet, the server closes the session of the client form the server side.

When the client detects disconnect from the server, check the reason. See https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L2337

Then call close_handler or error_handler.

That's disconnect sequence.

mqtt_cpp client can distinguish error or normal close. However, mqtt_cpp client can't distinguish the normal close is caused by MQTT disconnect packet sent by the client, or other reason. The server might close correctly if something error in the server happens. It could happen before and after MQTT disconnect packet sending.

You can store disconnect_requested information as follows:

```cpp
    // c is client

    bool disconnect_requested = false;

    // ...
    c->set_close_handler(
        [&]
        (){
            std::cout << "closed." << std::endl;
            if (!disconnect_requested) c->connect();
        });
    c->set_error_handler(
        [&]
        (boost::system::error_code const& ec){
            std::cout << "error: " << ec.message() << std::endl;
            if (!disconnect_requested) c->connect();
        });


{  // somewhere. might be in some handler.
    c->disconnect();
    disconnect_requested = true;
}   
```

Again, mqtt_cpp client can't know the actual reason of normal close, so mqtt_cpp shouldn't assume it.

**Comment by kleunen** [comment]
Hello @redboltz, 

indeed I am referring to the client and indeed the code sample you give is what I am doing now. And I understand now that the client sends a disconnect request to the server, and the server will close the socket on a normal disconnect operation. 

However I do feel that the mqtt_client should track whether a disconnect was requested. I think in your handle_close_or_error, when EOF occurs, it should be an error if this was done without the client requesting a disconnect, or it should be a close when the client did request a shutdown. 
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L2337

I suggest the following close handling:
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L771

```c++
void disconnect() {
        if (connected_ && mqtt_connected_) {
            close_requested = true;
            send_disconnect();
        }
    }
```

Line 
```c++
bool handle_close_or_error(boost::system::error_code const& ec) {
       // if (!ec) return false; (A successful close should also be handled ?)
        if (connected_) {
            connected_ = false;
            mqtt_connected_ = false;
            shutdown_from_server(*socket_);
        }
        if (ec == as::error::eof ||
            ec == as::error::connection_reset
#if defined(MQTT_USE_WS)
            ||
            ec == boost::beast::websocket::error::closed
#endif // defined(MQTT_USE_WS)
#if !defined(MQTT_NO_TLS)
            ||
#if defined(SSL_R_SHORT_READ)
            ERR_GET_REASON(ec.value()) == SSL_R_SHORT_READ
#else  // defined(SSL_R_SHORT_READ)
            ERR_GET_REASON(ec.value()) == boost::asio::ssl::error::stream_truncated
#endif // defined(SSL_R_SHORT_READ)
#endif // defined(MQTT_NO_TLS)
        ) {
            if(!close_requested)
               handle_error(ec);
            else
              handle_close();
            return true;
        }
        handle_error(ec);
        return true;
    }
````

I would say, this follows the asio convention more closely (every async operation results in the matching callback to be called with an error or success). disconnect -> close called (always success), an intermittent close is an error.

**Comment by redboltz** [comment]
@kleunen , your approach seems good :) I will implement it.
There is a related issue. It's about `force_disconnect()`.
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/client.hpp#L327
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L780

When the client calls `force_disconnect()`, the client closes the socket. Then `handle_close_or_error(ec)` is called with 'ec =  Bad file descriptor`. I'm not 100% sure ec's value. It might have various value depends on environment. e.g) WebSocket, TLS combination, Linux/Windows...

Anyway, what is the excepted behavior when the client calls `force_disconnect()`. I think that just calling `error_handler` is ok.

**Comment by kleunen** [comment]
Indeed I agree, if you can force_disconnect, you get an unclean shutdown, correct ? The server does not get informed of the close, so from mqtt perspective, this would be indeed an error and calling error_handler is ok.

**Comment by kleunen** [comment]
One more question: is error_handler always called on a socket error ? Or is it also called for protocol errors or when a subscribe fails or something like this ? Because if the error_handler is also used for other errors, then it would be good to be able to detect if the error is recoverable, or the client needs to disconnect and reconnect.

**Comment by redboltz** [comment]
> Indeed I agree, if you can force_disconnect, you get an unclean shutdown, correct ?

Yes.

> One more question: is error_handler always called on a socket error ? 

Yes.

> Or is it also called for protocol errors or when a subscribe fails or something like this ? 

No.
Each request after connection established has own handler. For example, [suback_handler](https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L520) is corresponding to `subscribe `, [connack_handler](https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L456) is corresponding to `connect`.

**Comment by kleunen** [comment]
ok, good. Then indeed, my proposed handler seems like a good approach :)

**Comment by redboltz** [comment]
I'm implementing it.
Some test cases report errors.

When MQTT broker returns connect_return_code except `accepted`,
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/connect_return_code.hpp#L16

first, connack_handler is called with connect_return_code. 
Then the broker close the socket from the broker(server) side.
So error_handler is called. Before the fix, close_handler is called. 

We have 3 choices after connack_handler is called.

1. call close_handler (current master behavior)
2. call error_handler (this fix behavior)
3. no handler is called

I think 3 is not good. Because MQTT protocol error and socket error (or close) are different. So the both of them are reported.

If the user want to call connect() again only in error_handler, 2 is good. 
It's a breaking change. 

Do you think 2 is good ?

**Comment by kleunen** [comment]
Yes, I agree option 2 is good here. Indeed, the user then in all cases has to perform reconnecting in only one location: the error_handler

**Comment by kleunen** [comment]
@redboltz I tested this, it works correctly. I get an error now, if the connection was broken unexpectedly, and I do a reconnect from the error handler. If I request a disconnect, on shutdown, the connection is shutdown cleanly and I get a closed handler call. This is very convenient.

**Comment by teddibaer** [comment]
Hi,

I just stumbled across this while searching for a reason why my client seems to sometimes have issues with reconnecting to the broker (with older 1.x verisons). I think I understand the new handling you propose in this situation, but may I request that this is somewhere more prominently documented with i.e. an example? I think this is a very common use-case and right now does not seem to be obvious how to handle this case (or at least I did not notice it).
Other from that: thank you for investing so much work into this. I really appreciate it!
