### ISSUE TITLE
test_broker.hpp, unused variable "cid"

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#178]
```
    bool try_connect(
        bool clean_session,
        con_sp_t const& spep,
        std::string const& client_id,
        boost::optional<mqtt::will> will) {
        auto it_ret = cons_.emplace(client_id, spep);
        if (!std::get<1>(it_ret)) {
            pending_.emplace_back(clean_session, spep, client_id, std::move(will));
            return false;
        }
        auto cid = boost::apply_visitor(
            make_lambda_visitor<std::string>(
                [&](auto const& con) {
                    return con->client_id();
                }
            ),
            spep
        );
        connect_proc(clean_session, spep, client_id, std::move(will));
        return true;
    }
```

`auto cid = boost::apply_visitor(`

cid isn't used.

Should this have been used in the call to connect_proc?

**Comment by redboltz** [comment]
> Should this have been used in the call to connect_proc?

I don't think so. cid and apply_visitor should be removed.

I forgot the history. Maybe I tried to get client_id from the endpoint at first.

**Comment by jonesmz** [comment]
I should elaborate on what I'm working on, and the reason why I'm sending so many pull requests and opening issues.

I'm working on a MQTT broker, and an MQTT client that will be used for an IOT (Internet of things) style application.

The biggest reason why I'm using mqtt_cpp is because it's C++, and uses boost. You've put together a great api. Many thanks.

The broker implementation that you have in test/test_broker.hpp is like 75% of what I needed, so I'm really thankful that you've released the code under the Boost license.

Have you considered promoting the code from test_broker.hpp into a real part of the mqtt_cpp project? I think that there are a lot of projects out there that would benefit from having such an easy to modify mqtt broker to use.

**Comment by redboltz** [comment]
The tests used to use test.mosquitto.org. But it was not good. Because accessing external network from CI is sometimes problematic.

So I implemented `test_broker.hpp`. Basically it is for test.

But It is also a good reference to implement a broker.

We can use very primitive broker:
https://github.com/redboltz/mqtt_cpp/blob/master/example/broker.cpp

I considered providing broker framework something like `include/mqtt/broker.hpp`. But it is not so easy. Broker implementation requirements are very diverse. In addition, many C++ programmers don't like **framework** approach including me ;)

So I stopped. Now, my priority is MQTT v5.

That's my current situation.

By the way, I also implementing proprietary MQTT broker using mqtt_cpp. As far as I can do, I will feedback something to mqtt_cpp.
