### ISSUE TITLE
handle_connack calls do_sync_write

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#237]
```
if (static_cast<std::uint8_t>(payload_[1]) == connect_return_code::accepted) {
    if (clean_session_) {
        LockGuard<Mutex> lck (store_mtx_);
        store_.clear();
        packet_id_.clear();
    }
    else {
        LockGuard<Mutex> lck (store_mtx_);
        auto& idx = store_.template get<tag_seq>();
        for (auto const& e : idx) {
            do_sync_write(e.message());
        }
    }
}
```

This has the potential to interfere with async_client.hpp

**Comment by redboltz** [comment]
## As is analysis
`mqtt_cpp` prohibit any API call except `force_disconnect()` between `connect()` called and connack handler invoked. Though not documented well.
So there is no chance to interrupt packet sending API calling.
The current situation is not the best but not harmful.

## To be
Implement two functions. One is `sync_process_stored_data()`. The other is `async_process_stored_data()`. The current implementation is moved to `sync_process_stored_data()`. And it is called from `sync_client`. And add the new `async_process_stored_data()`, it is called from `async_client()`. 
It is a little similar to `auto_pub_response`. They are triggered by receiving packet, not users function call.

## Implementing `async_process_stored_data()`
The function should be implemented carefully. Important point is when `store_` and `packet_id_` are cleared. Sync implementation is easy. When `do_sync_write()` returns, asio write the packets to the socket. In the async case, when `do_async_write()`'s callback handler is called, caller can erase coresspoinding `store_` and `packet_id_` one by one. And all callback is called, call `connack` handler for user.

**Comment by jonesmz** [comment]
Can you show me what part of the standard this section of code is implementing?

I wonder if using the clean_session flag that the client sent to the server is the right thing to do. Should it instead be checking the value of `bool session_present = is_session_present(payload_[0]);` ?

**Comment by redboltz** [comment]
Let me clarify your question?

You mean as follows?

```cpp
if (static_cast<std::uint8_t>(payload_[1]) == connect_return_code::accepted) {
    // if (clean_session_) {
    if (session_present) {  // session_present should be used here
        LockGuard<Mutex> lck (store_mtx_);
        store_.clear();
        packet_id_.clear();
    }
    else {
        LockGuard<Mutex> lck (store_mtx_);
        auto& idx = store_.template get<tag_seq>();
        for (auto const& e : idx) {
            do_sync_write(e.message());
        }
    }
}
```

**Comment by redboltz** [comment]
I think that I understand your question correctly.  And you are right.

Spec said that as follows:

---
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901078

If the Server accepts a connection with Clean Start set to 0 and the Server has Session State for the ClientID, it MUST set Session Present to 1 in the CONNACK packet, otherwise it MUST set Session Present to 0 in the CONNACK packet. In both cases it MUST set a 0x00 (Success) Reason Code in the CONNACK packet [MQTT-3.2.2-3].

* If the Client does have Session State and receives Session Present set to 0 it MUST discard its Session State if it continues with the Network Connection [MQTT-3.2.2-5].

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901230

The Session State in the Server consists of:

* The existence of a Session, **even if the rest of the Session State is empty**.
* The Clients subscriptions, including any Subscription Identifiers.
* QoS 1 and QoS 2 messages which have been sent to the Client, but have not been completely acknowledged.
* QoS 1 and QoS 2 messages pending transmission to the Client and OPTIONALLY QoS 0 messages pending transmission to the Client.
* QoS 2 messages which have been received from the Client, but have not been completely acknowledged.The Will Message and the Will Delay Interval
* If the Session is currently not connected, the time at which the Session will end and Session State will be discarded.
---

I want to confirm I understand the spec correctly.

|Step|Event|Previous server side SessionState|
|---|---|---|
|1|Client send CONNECT with CleanStart0|0|
|2|Server send CONNACK with SessionPresent0|Update to 1|
|3|disconnected|1|
|4|Client send CONNECT with CleanStart0|1|
|5|Server send CONNACK with SessionPresent1|1|
|6|disconnected|1|
|7|Client send CONNECT with CleanStart1|1|
|8|Server send CONNACK with SessionPresent0|Update to 0|

The server side SessionState is updated without subscribe/publish. Is that right?

**Comment by redboltz** [comment]
On MQTT v3.1.1, it wan unclear for me.

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718035

---

3.2.2.2 Session Present 

If the Server accepts a connection with CleanSession set to 0, the value set in Session Present depends on whether the Server already has stored Session state for the supplied client ID. If the Server has **stored Session state**, it MUST set Session Present to 1 in the CONNACK packet [MQTT-3.2.2-2]. If the Server does not have stored Session state, it MUST set Session Present to 0 in the CONNACK packet. 

---

The definition of "**stored Session state**" was unclear for me.

But on MQTT v5, it is clear for me.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901078

---

3.2.2.1.1 Session Present

If the Server accepts a connection with Clean Start set to 0 and the Server has **Session State** for the ClientID, it MUST set Session Present to 1 in the CONNACK packet, otherwise it MUST set Session Present to 0 in the CONNACK packet.

---

**Session State** is well defined now.
