### ISSUE TITLE
Support for message persistence

### ISSUE THREAD

**Issue by thoism** [redboltz/mqtt_cpp#294]
I have noticed that other MQTT client libraries support message persistence e.g. paho mqtt client libraries. Are there any plans for such a feature?

I would really like to switch to mqtt_cpp library which is a pure C++ header only library but message persistence is a feature I currently would like to have so this is the reason I am asking

**Comment by jonesmz** [comment]
What do you mean by message persistence?

**Comment by redboltz** [comment]
See https://github.com/redboltz/mqtt_cpp/wiki/Persistence
mqtt_cpp support persistence.
But the approach is different from paho and MQTT.js.
mqtt_cpp doesn't have `store` parameter on constructor or setter.
Instead of that, mqtt_cpp provides some functions.

## updating 
Call [set_serialized_handlers()](https://redboltz.github.io/contents/mqtt/classmqtt_1_1endpoint.html#acaf8bc427d46b88f2ce4d95d1b73728c) after construct the client and before calling `connect()`.

* `h_publish` is called just before the publish packet sending. You can store the message in your way.
* `h_pubrel` is called just before the pubrel packet sending. You can store the message in your way. Normally, overwrite stored publish message that has the same packet id.
* `h_remove` is called `puback` or `pubcomp` is received. You can remove the stored message that has the matched packekt id.

In my example, I use level-db to store.

## restoring
Call [restore_serialized_message()](https://redboltz.github.io/contents/mqtt/classmqtt_1_1endpoint.html#aa710a32bf5d1cd297c30f6233001f6dc). You call it after the client created and before `connect()` is calling.
This function restore one message. So you need to call it for all stored message. The store (insertion) order is the same as sending order after connection. So you need to call it old to new.
My example do that. level-db doesn't have order, so I added count in the payload and sort it before restoring. It is just PoC example, count is usually not a good choice. Timestamp is better. Because, persistence need to keep the order during reboot. (I will update the example in the future.)

## MQTT v5
The functions are for MQTT v3.1.1.
For v5, [set_v5_serialize_handlers()](https://redboltz.github.io/contents/mqtt/classmqtt_1_1endpoint.html#a3d9c2704b2e3bd6a90c2287c2f9c7a64) and [restore_v5_message()](https://redboltz.github.io/contents/mqtt/classmqtt_1_1endpoint.html#a76d4a070a29cfb96a4da468192e4533c)

## Design decision
I intentionally avoid introducing a store class. The store class usually contains storing way. e.g. level-db.
But user want to other way. The store class could have customization point. But it is complected for me.
So I choose callback functions and restore function.

## Other resources
Test codes might be helpful to implement your own storing mechanism.

https://github.com/redboltz/mqtt_cpp/blob/master/test/resend_serialize.cpp
https://github.com/redboltz/mqtt_cpp/blob/master/test/resend_serialize_ptr_size.cpp

**Comment by thoism** [comment]
I really appreciate your attention; your response is much clearer and concise than I could have ever expected. Thank you so much!
