### ISSUE TITLE
constexpr properties

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#335]
I'd like to have code like this in a headerfile, to share constants across projects.

```
static constexpr mqtt::v5::property::user_property_ref gc_successUserProp{"StatusCode", "Success"}
static constexpr mqtt::v5::property::user_property_ref gc_errorUserProp{"StatusCode", "Error"}
```

But currently the constructor of `user_property_ref` is not constexpr.

I'm fairly certain that boost::string_view is constexpr constructible, and std::string_view is as well.

So we should be able to add the constexpr keyword to the various _ref properties and be able to construct constexpr versions like above.

(Note that I'm compiling with C++17, so static initialization rules might be slightly different if you build with C++14)

**Comment by redboltz** [comment]
It is related to #320. I'd like to discuss based on executable code. I'm doing now. Please wait a couple of days.

**Comment by redboltz** [comment]
I just sent the PR #337. 

`mqtt::buffer` provides `string_view` with conditional life keeper. If life keeper is not given, `mqtt::buffer` is a pure view. If life keeper is given, `mqtt::buffer` holds it as a private member variable. 

https://github.com/redboltz/mqtt_cpp/pull/337/files#diff-8129b9d0908a07c08e3e8f033eae2a53R19

Properties and will have `mqtt::buffer` as their member variables. So we can switch **pure view** and **life keeping view**. The important point is their type is erased. Thanks to this feature, I can remove `*_ref` properties and I did it.

However, `mqtt::buffer` can't be literal type because the member variable (shared_ptr_array) destructor is non trivial. That means the properties that have `mqtt::buffer` can't be literal type.

* pros
  * Simpler property type
* cons
  * Properties that have `mqtt::buffer` can't be defined as constexpr.

I believe that I can add `*_ref` properties that uses `mqtt::string_view` instead of `mqtt::buffer`, but I think that simpler property type is more important.

What do you think?

**Comment by jonesmz** [comment]
I think that using MQTT::buffer is more important than constexpr.

Plus, I just found out about inline static from c++17, which might solve my problem anyway.

**Comment by jonesmz** [comment]
If you're satisfied with my reply, we can close this issue.

**Comment by redboltz** [comment]
Ok, thanks.
