### ISSUE TITLE
Replace do_combi_test with do_combi_test_sync

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#355]
I think we should make mqtt::client into only a "base class", and require users of mqtt_cpp to use either async_client, or sync_client.

**Comment by redboltz** [comment]
I'm not sure what you mean.

For users,
* `mqtt::async_client` can use only async APIs.
* `mqtt::sync_client` can use only sync APIs.
* `mqtt::client` can use both async/sync APIs for expert users.

Do you mean for only test?

**Comment by jonesmz** [comment]
I mean that mqtt::client should not be used by users. I think it is dangerous.

**Comment by redboltz** [comment]
That's why I say it is for expert users. I think that we agreed this topic before.
I have no plan that client to be private.

Before I implemented stored packet sending code after connack on async_client, it is send as sync. There are other similar case. Sending some application stored messeges at controlled point e.g. after connack or after user defined protocol initial phase, sending sync messages in convenient and other place the same client use async apis.

It seems that the PR #357 is focused on test. It could be acceptable.

**Comment by redboltz** [comment]
> That's why I say it is for expert users. I think that we agreed this topic before.

I'm sorry, I noticed that I misunderstood. I mean #196. You are not in #196.

Anyway, I want to keep async_client, sync_client, and client. See https://github.com/redboltz/mqtt_cpp/wiki/Sync-vs-Async

---

Current test code is

* sync_client
  * test sync_client and client
* async_client
  * test async_client and client

So test for client is redundant. Because sync_client and async_client use client internally. But factory functions of client should be tested.

I don't check #357 yet but I think that the following is better.

* sync_client
  * test sync_client
* async_client
  * test async_client
* client
  * test factory functions only (minimal connect ?).
