### ISSUE TITLE
connect handler argument of connect not invoked in case of connection failure

### ISSUE THREAD

**Issue by ropieur** [redboltz/mqtt_cpp#420]
I wrote a small mqtt client (asynchronous), but the passed argument handler is not invoked in case if it cannot connect to the broker. Example:

```
    boost::asio::io_context ioc;
    auto client = mqtt::make_async_client(ioc, "localhost", 1883);
    client->set_clean_session(true);
    client->connect([](const auto &error){
        std::cout << "Connect handler error=" << error.message()) << std::endl;
    });
```
Reading the documentation, async_client should expose async_* methods, but **connect** does not follow the rule.

**Comment by redboltz** [comment]
> Reading the documentation, async_client should expose async_* methods, but connect does not follow the rule.

Yes. connect is always behave asynchronously. It is existing problem. Connecting phases are TCP, TLS, WebSocket, and MQTT, they are complicated. So far, we only have asynchronous one. Document should be updated.

In your code, you need to run `ioc.run()`, and set `set_close_handler()` and `set_error_handler()`. If underlying layer's error happens, they might be called.

**Comment by redboltz** [comment]
NOTE:   
read is always do asynchronously.  Even if we use only sync APIs, we need to call `ioc.run()` and required to do asynchronous callback based programming.

**Comment by ropieur** [comment]
> read is always do asynchronously. Even if we use only sync APIs, we need to call `ioc.run()` and required to do asynchronous callback based programming.

I find this way of designing disturbing compared to boost asio. So what is the difference between sync and async calls?

**Comment by ropieur** [comment]
> In your code, you need to run `ioc.run()`, and set `set_close_handler()` and `set_error_handler()`. If underlying layer's error happens, they might be called.

I think that the handler set by **set_error_hander** can be triggered from eveywhere, so difficult to register a specific error handling depending on the source of error.
Example: when the client tries to connect, but fails because the broker is not running, I'd like to start a timer that retries the connection on a regular basis. If an error occurs during a publish or a subscribe, likely I would like to adopt a different error handling. I don't see how I could manage this variability.

**Comment by redboltz** [comment]
> Reading the documentation, async_client should expose async_* methods, but connect does not follow the rule.

Sync API: Use `write()` of boost asio. You don't need to care about data lifetime that you pass to APIs except QoS1 and QoS2 publish with reference(`as::buffer` and `mqtt::buffer` with no life keeper) parameter. The function returns when `write()` returned. It means send data is copied to OS (driver?) buffer.

Async API: Use `async_write()` of boost asio. You need to care about data lifetime if you pass as reference parameter. For keep lifetime, you can pass `life_keeper` parameter. The function returns when `async_write()` returned. It is faster that sync APIs.

**Comment by redboltz** [comment]
|handler|meaning|
|---|---|
|close_handler|connection is closed by disconnect packet|
|error_handler|connection is closed other reasons|

If you want, you can retry connecting.
Typical implementation is wait some seconds and retry connection.

Other errors are completely different meaning. For `subscribe()`, the error information contains `SUBACK` packet. So if you want to handle subscribe error, call `set_suback_handler()`. It is called not only error but also success.
The handlers directly reflected MQTT specification.
See [MQTT v3.1.1 Spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) or [MQTT v5 Spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html).

**Comment by redboltz** [comment]
NOTE: Even If suback returns error (reason_code is not successful), then connection is kept.

**Comment by ropieur** [comment]
In order to summarize, connect calls
- **close_handler** when the connection is properly closed by the broker
- **error_handler** when the connection is closed for other reasons (e.g. communication issue at socket level)
- **connection_handler** argument when the connection is fully established at socket level. In this case, I guess that the error argument in the connection_handler is an error reported by the broker.

**Comment by redboltz** [comment]
After #435 fixed, I noticed that the reason of error callback confusion.

As @ropieur mentioned, `connect(async_handler_t)` and error handler set by `set_error_handler()` are confusion. I noticed that they are redundant.

Let me explain the design history.

`connect(async_handler_t)` is for clients and `start_session(async_handler_t)` is for servers.
The both has the parameter `async_handler_t`. The primary purpose of `async_handler_t` is keeping session's lifetime. The passed handler is expected capture `std::shared_ptr<endpoint_t>` to keep session's lifetime.

At that time, I only know `std::function` and lambda expression capture can do that.
So I choose it. Even if I use `std::function` as the life keeper, I invoked it. I didn't well considered at that time. I just thought that interface for user is `std::function` so user expects it is invoked when session lifetime is over. User can know the end of session by `set_error_handler()` and `set_close_handler()` too. So invoking `async_handler_t` is something redundant.

Thanks to @jonesmz, now I know `any` is appropriate for life keepers.

I leaned if I use `std::function` for life keeper, I would have a problem invoke the function or not. If I invoke it, the callback is something redundant. If I don't call it, user might confused because they passed function but is is never invoked.

I think that I should replace `async_handler_t` with `any`.

It is related to #430. @jonesmz, please wait little more.

**Comment by redboltz** [comment]
#442 will fix the issue. 

`async_handler_t` is not completely removed. `async_handler_t` for `async_*()` APIs such as `async_publish()` are remained. They notify asynchronous processing has been finished. That means the message is copied into the OS/driver buffer. They are one request / one response model.

`async_handler_t` for `connect()` and `start_session()` are removed. They start a session. It is different from `async_*()` APIs. We can know the end of session by`set_close_handler()` and `set_error_handler()`.

**Comment by jonesmz** [comment]
Something to consider for the future is an an optional feature for async/sync client, where a handler is called when the published packet has received a puback.  This would allow applications to do an action when the data has been guaranteed to be seen by the broker.

**Comment by redboltz** [comment]
@jonesmz , user can handle publish using `set_puback_handler()`, `set_pubrec_handler()`, and `set_pubcomp_handler()`. If user want to map `publish()` call with user's callback, then user can implement a map that packet_id and user callback. It can be implemented as a wrapper of `publish()` function. It is NOT a part of mqtt_cpp, so far. I want to be careful to add APIs because we need to manage them.

**Comment by jonesmz** [comment]
Well that's basically what I'm saying. Very few users want to implement that behavior themselves. If there was a high level async/sync client that offered this functionality, most users of mqtt_cpp would want to use that api instead of puback / pubrec /pubrel / pubcomp

**Comment by redboltz** [comment]
Ok, could you create an issue for that feature request. I think that it is separated from the issue.

> puback / pubrec /pubrel / pubcomp

Do you mean `set_pub*_handler()` ? mqtt_cpp already has automatice puback / pubrec /pubrel / pubcomp sending functionality.

**Comment by jonesmz** [comment]
> Do you mean set_pub*_handler() ? mqtt_cpp already has automatic puback / pubrec /pubrel / pubcomp sending functionality.

Right, I'm aware. I meant the general concept of "Hey, mqtt_cpp, publish this message and then let me know when the server has it", as a one step operation.

**Comment by jonesmz** [comment]
@ropieur is this still an issue for you?

**Comment by ropieur** [comment]
Sorry for the late response. From my side, this ticket is no longer an issue.
Just a remark: It happened that the connection between the client and the broker has been lost (connected() became false), but the async_client didn't notify it (close handler was not invoked).  Unfortunately, the occurrence of this issue is very low and impossible to reproduce in isolation. But when it occurs on my client, the service is completely down.
I prefer to confirm the issue is not on my side before reporting it.
