### ISSUE TITLE
Support for gcc -pedantic option

### ISSUE THREAD

**Issue by ropieur** [redboltz/mqtt_cpp#458]
Hi @redboltz,
The latest version of mqtt_cpp fails to compile with -pedantic due to public destructors in some base classes with virtual functions.

E.g
```
.../include/mqtt/client.hpp:950:17:   required from here
.../include/mqtt/client.hpp:44:7: error: ‘class mqtt::client<mqtt::tcp_endpoint<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::io_context::strand> >’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class client : public endpoint<std::mutex, std::lock_guard, PacketIdBytes> {
```

**Comment by redboltz** [comment]
I added `-pedantic` to travis-ci on g++.

https://github.com/redboltz/mqtt_cpp/blob/master/.travis.yml#L98


https://travis-ci.org/redboltz/mqtt_cpp/jobs/588744409#L1097

It seems that no error is reported.
I don't see any problem. If you understand what the problem is, could you write a PR?
It is better to discuss based on the code.

**Comment by ropieur** [comment]
@redboltz,
The issue is reported by g++ 7.4.0 under ubuntu 18.04
I forked the project and cloned it locally, but I don't see how to solve the issue.
I thought that the issue was due to public non virtual dtor in base classes and should be protected, but it is already the case for base class endpoint.
The compiler complains for the derived class client while instantiating factory functions `make_client*`.
Moreover, `client` serves as a public base class for `async_client`, so I don't see how to solve the issue in this specific case (theoretically, it is possible to keep a `async_client` through a base `client` ref/pointer)

**Comment by redboltz** [comment]
I guess that

**Comment by redboltz** [comment]
I guess that it is gcc bug. Try newer gcc.

**Comment by redboltz** [comment]
You can test various versions of gcc here:
https://wandbox.org/permlink/uUibbsHBlOODSUQb

Unfortunately, gcc 7.4.0 is not listed but you can write a minimal and complete code that reproduces the issue.

**Comment by jonesmz** [comment]
This is also reported by clang, and I dug into it a bit.

The reason for the warning is that `mqtt_cpp::client` can be (theoretically) used as the "type" of a smart pointer, (one would have to inherit from it to provide implementations for the virtual functions, of course), and therefore deleted.

I believe the correct course of action is that
- `async_client
- `sync_client`
- `client`

each should have their destructors made private.

The current mqtt_cpp API is such that the end-user must either use callable_overlay<>, which provides implementations of all of the virtual functions, or the end-user must provide their own implementation of each virtual function.

However, in neither of those situations, should the end user ever be doing
```cpp
MQTT_NS::client* myClient;
delete myClient;
```

They should only ever do

```cpp
most_derived_client_type* myClient;
delete myClient;
```

From the end users perspective, we can fix this without changing *valid* uses of the API. But (unlikely) some invalid uses of the API may experience compiler failures.

`std::shared_ptr<client> p = std::make_shared<MQTT_NS::callable_overlay>(...);`

is perfectly valid, because the deleter functor that std::shared_ptr stores is itself type-erased, but internally stores the type of the object created with std::make_shared.
