### ISSUE TITLE
Websocket connection to mosquitto broker fails

### ISSUE THREAD

**Issue by Paul92** [redboltz/mqtt_cpp#609]
I am trying to setup a websocket client for a mosquitto broker.

The config for the broker is:

```
port 1883
protocol mqtt

listener 9001
protocol websockets
```

When using the `no_tls_client.cpp` example, everything works as expected. With the `no_tls_ws_client.cpp` example, it simply hangs with the following backtrace:

```
epoll_wait 0x00007f448a27d5ca
boost::asio::detail::epoll_reactor::run epoll_reactor.ipp:471
boost::asio::detail::scheduler::do_run_one scheduler.ipp:431
boost::asio::detail::scheduler::run scheduler.ipp:200
boost::asio::io_context::run io_context.ipp:63
main no_tls_ws_client.cpp:125
__libc_start_main 0x00007f448a1a5153
_start 0x0000561afb702bee
```

The broker does not report any incoming connection.

A similar client in Python, using the paho library works:

```
import paho.mqtt.client as mqtt
import ssl

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    client.subscribe("$SYS/#")


def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))

client = mqtt.Client(client_id='test', clean_session=True, transport='websockets')
client.on_connect = on_connect
client.on_message = on_message

client.connect("localhost", 9001, 60)
client.loop_forever()
```

Any advice on fixing this issue?

**Comment by redboltz** [comment]
## debugging
Unfortunately, mqtt_cpp doesn't have logging functionality yet. So you need to use a debugger or insert debug print code.
I set up the mosquitto environment and got the same result.

It seems that websocket handshake is successfully finished at least on the client side.
Then the client send MQTT CONNECT packet.

You can check the following code:

https://github.com/redboltz/mqtt_cpp/blob/8f2fa503f11eb6b52b94b55727c7aecb2046b1fe/include/mqtt/endpoint.hpp#L8077-L8115

And successfully write to boost asio:
https://github.com/redboltz/mqtt_cpp/blob/8f2fa503f11eb6b52b94b55727c7aecb2046b1fe/include/mqtt/endpoint.hpp#L8525-L8533

So from the client side, start waiting MQTT CONNACK packet but doesn't received.

The receiving code is as follows:
https://github.com/redboltz/mqtt_cpp/blob/8f2fa503f11eb6b52b94b55727c7aecb2046b1fe/include/mqtt/endpoint.hpp#L3935 -L3945

This function is called but the lambda expression (receiving handler) is not called.

## Other server
I tested mqttjs/mqtt-server instead of mosquitto.

https://github.com/mqttjs/mqtt-server

test_server.js

```js
var mqttServer = require('mqtt-server');

var servers = mqttServer({
  mqtt: 'tcp://localhost:1883',
  mqtts: 'ssl://localhost:8883',
  mqttws: 'ws://localhost:1884',
  mqtwss: 'wss://localhost:8884'
}, {
  emitEvents: true // default
}, function(client){
  client.connack({
    returnCode: 0
  });
});

servers.listen(function(){
  console.log('listening!');
});
```

package.json

```js
{
  "name": "mqtt-server-example",
  "version": "0.1.0",
  "description": "test server",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "mqtt-server": "0.1.0"
  }
}
```

Run command:

```sh
> npm install
> node test_server.js
```

It works as I expected.

So the results are

|server|client|result|
|---|---|---|
|mosquitto|mqtt_cpp|ng|
|mqtt_cpp|mqtt_cpp|ok|
|mqttjs|mqtt_cpp|ok|

I think that the next step is analyzing mosquitto behavior. 
Does mosquitto receive CONNECT packet? And then send CONNACK packet?

**Comment by bbbrian94** [comment]
is this issue still open? recently consider to use this with mosquitto for my new app

**Comment by redboltz** [comment]
I'm not sure. I think that it depends on mosquitto. mqtt_cpp works well with mqtt_cpp server and MQTT.js server.
At least, mqtt_cpp doesn't receive CONNACK packet from mosquiito, at that time.

**Comment by redboltz** [comment]
Finally, I found the solution. mosquitto websocket seems to require subprotocol mqtt.
See #735
