### ISSUE TITLE
 bind the client with a local address

### ISSUE THREAD

**Issue by zaley2000** [redboltz/mqtt_cpp#616]
The client can't bind a local endpoint, although the server can do.  If the computer has more than one net interface card. and only one  can be connected to the broker,how can do ?

**Comment by jonesmz** [comment]
@zaley2000 When you say it can't bind a local endpoint, what do you mean?

The client does not bind an interface and wait for an incoming connection. That's the broker's job.

**Comment by ineffective** [comment]
I believe that zaley2000 asked what should be done in case of multi-home machine or one that acts as a router between two other or one that simply has multiple interfaces because it has wi-fi, gsm and ethernet interfaces (possibly all up). I think that answer is simple: interface will be selected using machine's networking configuration. I believe it can be safely closed, especially since it has been hanging inactive for 5 months now.

**Comment by jonesmz** [comment]
The right way to handle this, if @ineffective is correct in interpreting the question, is to create the socket before calling "connect" or "async_connect" and pass the socket you created into the function call.

@redboltz This issue can probably be closed now.
