### ISSUE TITLE
Use of strand

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#645]
I've been trying to make improvements to mqtt_cpp to simplify packet processing / parsing.

@redboltz, You identified before that having socket as template parameter for endpoint class + templated recursive packet parse functions caused long compile times.

Today I wanted to experiment with co-routines on packet parse function, and had this problem:

Because socket is type erased, I cannot use boost coroutine completion token style, which requires access to `executor_type` typedef.

So I investigated why `tcp_endpoint `and `ws_endpoint` exist, and see that they have strand as main feature.

I propose these changes to make mqtt_cpp better.

1. Move strand out of `tcp_endpoint` and `ws_endpoint`, into `endpoint` directly. All calls to async_write / async_read wrapped in strand::wrap().
2. Now that tcp_endpoint does not have strand, it is just thin wrapper around `as::ip::tcp::socket` or `as::ssl::stream<as::ip::tcp::socket>`, remove it and use `as::ip::tcp::socket` or `as::ssl::stream<as::ip::tcp::socket>` directly instead.
3. Add socket template back to `endpoint` class, remove type erasure.
4. change `ws_endpoint` `write`, `async_write`, and `async_read`, to `write_some`, `async_write_some`,` async_read_some`, this allows for use of `as::write`, `as::read`, `as::async_read`, which is important for support of completion token for co-routines.
5. Then replace calls to `socket->write`, `socket->read`, `socket->async_read` with `as::write`, `as::read`, `as::async_read`
6. Make some processing functions, like `process_nbytes`, `process_binary` support the completion token concept by some changes to parameters.
7) Change `process_*` functions that parse different sections of packet into co-routine functions, to reduce template instantiation and reduce compile times, and make easier to understand.

These changes should be non-breaking for end-user code. Internal changes only.

**Comment by redboltz** [comment]
I think that your idea seems good.

I introduced Boost.TypeErasure, but I know it provides limited interface. I reluctantly use it to solve longer compile times issue.
If we can remove it, it is better.

> So I investigated why `tcp_endpoint `and `ws_endpoint` exist, and see that they have strand as main feature.

I think that strand is not a main reason to use `tcp_endpoint` and `ws_endpoint`.
Boost.Beast provides only chunk read functionality for websockets. It is different from `as::ip::tcp::socket`. I want to have `async_read()` that has a expected sized buffer. Thee completion handler will call if buffer is received expected size.
I need to implement that `async_read()` so I wrote `ws_endpoint`.

https://github.com/redboltz/mqtt_cpp/blob/4951a48b4050d782fc2853ecce4a349b3fb357ba/include/mqtt/ws_endpoint.hpp#L104-L164.

This is adaptor code. *1 It uses completion token as a callback. I'm not sure it works well with coroutine. But I guess that it is no problem.

After I implemented `ws_endpoint`, I added thin wrapper for `as::ip::tcp::socket`. That is `tcp_socket`.

As you mentioned,  `ws_endpoint` and `tcp_socket` wraps strand processing. But it is not essential reason to exist them.
So I think that move strand processing to endpoint is no problem except the following point.

*1
`ws_endpoint` calls `async_read()` several times internally with strand. See
https://github.com/redboltz/mqtt_cpp/blob/4951a48b4050d782fc2853ecce4a349b3fb357ba/include/mqtt/ws_endpoint.hpp#L138

I guess that `ws_endpoint` need to access to strand. So you need to prepare the way to access to the strand from `ws_endpoint`.


> 7. Change process_* functions that parse different sections of packet into co-routine functions, to reduce template instantiation and reduce compile times, and make easier to understand.

I'm not sure this point. Do you mean boost asio's coroutine? mqtt_cpp supports C++14 and it doesn't have standard coroutine.

----

Another point. *2
The current my client code needs to strand post() to the endpoint.
In order to do that, I call `socket()` function
https://github.com/redboltz/mqtt_cpp/blob/4951a48b4050d782fc2853ecce4a349b3fb357ba/include/mqtt/endpoint.hpp#L3928-L3938

And then, call `post()` function.
https://github.com/redboltz/mqtt_cpp/blob/4951a48b4050d782fc2853ecce4a349b3fb357ba/include/mqtt/tcp_endpoint.hpp#L109-L115



> These changes should be non-breaking for end-user code. Internal changes only.

It's very nice!

I think that I can accept that *2 code would become doesn't work. If you provide a way to strand post() at the endpoint, I update my client code.
