### ISSUE TITLE
Assertion in broker

### ISSUE THREAD

**Issue by kleunen** [redboltz/mqtt_cpp#768]
I am still getting an assertion in the broker:

broker: /home/pi/mqtt_cpp/include/mqtt/endpoint.hpp:9103: void mqtt::endpoint<std::mutex, lock_guard, 2>::send_connack(bool, variant<mqtt::connect_return_code, v5::connect_reason_code>, v5::properties) [Mutex = std::mutex, LockGuard = lock_guard, PacketIdBytes = 2]: Assertion `false' failed.
Aborted

it is this assertion:
https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/endpoint.hpp#L9137

**Comment by redboltz** [comment]
It is caused by the broker sends connack but the `version_` is neither v3_1_1 nor v5.

`version_` is set at the only two location.

One is 

https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/endpoint.hpp#L4877-L4879

the other is

https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/endpoint.hpp#L6666-L6693

Broker uses the latter.

Before the `version_` is set, the broker create endpoint using the following constructor.

https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/endpoint.hpp#L189-L195

The version is set by server.hpp

https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/server.hpp#L143-L145

The initial value is undetermined.

https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/server.hpp#L192

The example broker doesn't pass version parameter.
https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/example/broker.cpp#L18

So the server creates endpoint using default version_ (aka undetermined)
https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/server.hpp#L176

The broker send connack in the connack handler.

https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/broker/broker.hpp#L767
https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/broker/broker.hpp#L773
https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/broker/broker.hpp#L787
https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/broker/broker.hpp#L787

But I found one exception case.

This is it.
https://github.com/redboltz/mqtt_cpp/blob/abb4f525d9eec4e6c7cce2c770d3bffa66f95314/include/mqtt/broker/broker.hpp#L323-L335

When the broker get protocol_error, and the underlying connection is still established, then call connack with protocol_error.
It seems that the reason of assertion failed.
Because at that time, MQTT is not connected. That means `version_` of endpoint is not determined yet. The broker shouldn't send connack in this situation.
I will fix it soon.

**Comment by kleunen** [comment]
But then I would have to see a protocol error before the connack is send right ? Because I have logging enabled

**Comment by kleunen** [comment]
or maybe connection is closed before mqtt connection establishement is complete, and this caused the error_handler to be called ?

**Comment by redboltz** [comment]
I guess that the client sends  CONNECT packet with something protocol error.

**Comment by redboltz** [comment]
> or maybe connection is closed before mqtt connection establishement is complete, and this caused the error_handler to be called ?

If broker detects underlying layer's disconnection, then

```cpp
  else if (sp->underlying_connected()){ 
```

returns false. So the assertion failed doesn't happedn.

If you get the backtrace when the assertion fail happens, it is helpful for debugging.

**Comment by kleunen** [comment]
yes, let me apply your fix and then try to get backtrace.

**Comment by kleunen** [comment]
It seems stable now with fix
