### ISSUE TITLE
How do you set a timeout for a client connection? 

### ISSUE THREAD

**Issue by Radagan** [redboltz/mqtt_cpp#804]
This question is very close to mine and I'm trying to follow it's advice:
https://github.com/redboltz/mqtt_cpp/issues/610#

I have an issue with AWS IoT Core that came up in testing, where it waits almost twenty minutes to tell me that my address range for the port is incorrect. So, the process waits at client_mqtt->connect(ec) below until Amazon finally sends the error. 

I'm trying to follow the advice in #610, but I have the problem that my timer doesn't run until ioc.run() and that's after my call to connect. So, I think I'm missing something important.

Is there an easy way to set a timeout on the call to connect? I'm using the sync client.

Where client_mqtt is:
```
client_mqtt = MQTT_NS::make_tls_sync_client(ioc, broker_url, broker_port, mqtt::protocol_version::v3_1_1);
```

Here's the relevant code:
```
boost::asio::deadline_timer timer(ioc, boost::posix_time::seconds(30));
            timer.async_wait([this](const boost::system::error_code& error) {
                if (error != boost::asio::error::operation_aborted) {
                    spdlog::warn("[MQTT {}] Timeout connecting to broker.", broker_id);
                    client_mqtt->disconnect();
                }
            });
            mqtt::error_code ec;
            client_mqtt->connect(ec);
            timer.cancel();
            if(ec) {
                // error handling removed for posting here...
            }
            spdlog::info("[MQTT {}] Client entering ioc run loop.", broker_id);
            ioc.run();
```

**Comment by redboltz** [comment]
I think that you need to use `client` instead of `sync_client`.

On `sync_client`, there is no way to timeout because boost::asio doesn't support timeout.

`connect()` calls

https://github.com/redboltz/mqtt_cpp/blob/e0d35ca6c90bfdf7c0af17b66efcee356c6c8cf7/include/mqtt/client.hpp#L1237-L1248

internally.

First, call `resolve()`.
https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/reference/ip__basic_resolver/resolve.html
There is no timeout version.

Then, call `connect()`
https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/reference/connect.html
There is no timeout version, too.

I found a related Q&A on the stackoverflow.
https://stackoverflow.com/questions/32692195/set-timeout-for-boost-socket-connect
It seems that the answer uses `async_connect()`.

Using `client` instead of `sync_client` is pretty difficult.
https://github.com/redboltz/mqtt_cpp/wiki/Sync-vs-Async#client-expert-only

You need to avoid sync sending API calling during async send processing.

You can call `client::async_connect()` instead of `sync_client::connect()`.
You cannot call sending API until connack handler is called.
And then, you can call only sync APIs. 
I'm not 100% sure but I think that it works.

**Comment by Radagan** [comment]
@redboltz Thank you. I encapsulate the sync client in a class of my own. In the end, I implemented a std::future to abort the connect in the layer above that owns my class. What I did works, but it's not very elegant. Considering the pitfalls above, would you consider adding a timeout feature for connect in the future?

**Comment by redboltz** [comment]
> Considering the pitfalls above, would you consider adding a timeout feature for connect in the future?

If boost asio's `connect()` and `resolve()` would support timeout, then mqtt_cpp would support the timeout.

**Comment by redboltz** [comment]
I found https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/example/cpp11/timeouts/blocking_tcp_client.cpp
I think that it is helpful to implement timeout version of connect() for sync_client.
I will try it when I have a time. Unfortunately I don't have much time now.
