### ISSUE TITLE
Working with non-literal strings while subscribing or preparing a will message

### ISSUE THREAD

**Issue by bheisen** [redboltz/mqtt_cpp#831]
This is more a question rather than a bug report.

I am puzzled how to use subscriptions topics which I am dynamically having available as `std::string`, i.e.:

```c++
typedef std::vector<std::tuple<MQTT_NS::string_view, MQTT_NS::subscribe_options>> Topics;
Topic generate_topics () {
  Topics topics;
  const std::string generated_topic("my/dynamic/topic");
  topics.push_back({generated_topic, MQTT_NS::qos::at_least_once});
  return topics;
}
```
I tried with `std::shared_ptr` and many different things without success, the string_view seems to loose the reference to the allocated string.

Similar problem occurs with preparing a will message.

Any help is appreciated (surely I am misunderstanding how to correctly use buffer / string_view concepts).

VERSION: current master

**Comment by redboltz** [comment]
When you use string_view, you need to manage viewed string lifetime by yourself. It is not only for mqtt_cpp but also all C++ libraries.
In your code, the variable `generated_topic` lifetime is over when the function `generate_topics()` is returned so the `std::get<0>(Topics)` becomes dangling reference.

```cpp
    std::string s1 = "mqtt_client_cpp/topic2_1"; // or call generate_topic() that returns std::string
    std::string s2 = "mqtt_client_cpp/topic2_2"; // or call generate_topic() that returns std::string
    c->subscribe(
            std::vector<std::tuple<MQTT_NS::string_view, MQTT_NS::subscribe_options>>
            {
                 { s1, MQTT_NS::qos::at_least_once },
                 { s2, MQTT_NS::qos::exactly_once }
            }
    );
````
This code is safe. You can also create std::vector<std::string>  in your function.
Then create `std::vector<std::tuple<MQTT_NS::string_view, MQTT_NS::subscribe_options>>` from `std::vector<std::string>`.
The important point is `std::vector<std::string>` should be outside of the function.
This means you need to manage `std::vector<std::string>` lifetime.

```cpp
    c->subscribe(
        std::vector<std::tuple<MQTT_NS::buffer, MQTT_NS::subscribe_options>>
        {
            { MQTT_NS::allocate_buffer("mqtt_client_cpp/topic2_1"), MQTT_NS::qos::at_least_once },
            { MQTT_NS::allocate_buffer("mqtt_client_cpp/topic2_2"), MQTT_NS::qos::exactly_once }
        }
    );
```

This approach is simpler. You can create MQTT_NS::buffer using MQTT_NS::allocate_buffer().
Is owns itself lifetime. You can treat it as std::string.
You can call MQTT_NS::allocate_buffer() in your generate_topics() and returns std::vector<std::tuple<MQTT_NS::buffer, MQTT_NS::subscribe_options>>>. Lifetime is automatically managed.


NOTE: You can use `mqtt::` namespace instead of `MQTT_NS::`. `MQTT_NS` is for someone want to use different name from `mqtt::`.

**Comment by redboltz** [comment]
This is PoC code using string_view.

```cpp
                auto generate_topics =
                    [&] {
                        return std::vector<std::tuple<std::string, MQTT_NS::subscribe_options>> {
                            { "mqtt_client_cpp/topic2_1", MQTT_NS::qos::at_least_once } ,
                            { "mqtt_client_cpp/topic2_2", MQTT_NS::qos::exactly_once }
                        };
                    };

                auto params = generate_topics();
                std::vector<std::tuple<MQTT_NS::string_view, MQTT_NS::subscribe_options>> view;
                for (auto const& e : params) view.emplace_back(std::get<0>(e), std::get<1>(e));
                c->subscribe(view);
```

This is PoC code for allocate_buffer(). I recommend this.

```cpp
                auto generate_topics =
                    [&] {
                        return std::vector<std::tuple<MQTT_NS::buffer, MQTT_NS::subscribe_options>> {
                            { MQTT_NS::allocate_buffer("mqtt_client_cpp/topic2_1"), MQTT_NS::qos::at_least_once } ,
                            { MQTT_NS::allocate_buffer("mqtt_client_cpp/topic2_2"), MQTT_NS::qos::exactly_once }
                        };
                    };
                c->subscribe(generate_topics());


```

**Comment by bheisen** [comment]
Wow, thank you for the prompt response @redboltz !

Yes, I believe it's exactly the `MQTT_NS::allocate_buffer` that I was looking for. This will solve my issues, thanks!
