### ISSUE TITLE
mqttv5 for quic

### ISSUE THREAD

**Issue by ganggangliu** [redboltz/mqtt_cpp#985]
When will the development of MQTT based on QUIC, supporting version 5, be available? Currently, there are many applications in the field of connected vehicles.

**Comment by redboltz** [comment]
mqtt_cpp has no plan to support quic. 
See current mode https://github.com/redboltz/mqtt_cpp#mqtt-clientserver-for-c14-based-on-boostasio

async_mqtt could support QUIC in the future. In order to do that, Boost.Asio based QUIC library is required.
It seems that some of such libraries are developing now, but AFAIK, they are still under construction.
